server:
  port: 8081
management:
  endpoint:
    health:
      show-details: always
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - env
          - health
          - info
          - refresh
spring:
  application:
    name: corp-notifications-api
  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers:
            - ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
      bindings:
        dispatcher-in-0:
          contentType: application/json
        dispatcher-out-0:
          producer:
            requiredGroups:
              - email
          contentType: application/json
        dispatcher-out-1:
          producer:
            requiredGroups:
              - whatsapp
          contentType: application/json
