server:
  port: 8085
management:
  endpoint:
    health:
      show-details: always
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - env
          - health
          - info
          - refresh
spring:
  application:
    name: corp-notifications-audit
  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers:
            - ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
      bindings:
        audit-in-0:
          destination: sendEmail-out-0
          contentType: application/json
        audit-in-1:
          destination: sendWhatsapp-out-0
          contentType: application/json
